POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "MZB",
    "number": "012-345-6789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json
{
    "name": "Merlin"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json
{
    "number": "111-111-1111"
}
